# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'NestedScrollView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NestedScrollView
  pod 'MJRefresh'

  target 'NestedScrollViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NestedScrollViewUITests' do
    # Pods for testing
  end

end
